[package]
name = "snake_rust"
version = "0.1.0"
authors = ["sfadiga <sfadiga at gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy = "0.2.0"
crossterm="*"
rand = "*"
